first
Improsing/Todoist-project pull request #1
Opened 2024-05-22 17:59 UTC by Improsing

2024-05-22 21:26 UTC, robotomize requested changes
Привет, к сожалению приложение при запуске не отрабатывает. ui пустой и невозможно создать задачу. В консоль логе ошибки js. Запустите и отладьте приложение, чтобы можно было проверить его работу через ui как это указано в задании, потом перейдем к ревью кода

2024-05-23 13:42 UTC, Improsing commented
> Привет, к сожалению приложение при запуске не отрабатывает. ui пустой и невозможно создать задачу. В консоль логе ошибки js. Запустите и отладьте приложение, чтобы можно было проверить его работу через ui как это указано в задании, потом перейдем к ревью кода

![ff](https://github.com/Improsing/final-project-go/assets/153368437/6134f939-59d1-42df-92e3-84fd2d417818)
У меня всё отлично работает, и тесты проходит)

2024-05-23 19:09 UTC, robotomize approved these changes
Привет, да, проблема в слешах, неплохая работа, основная задача выполнена. Но есть несколько пробелм, я их указал в комментах, самая главная заключается в том что когда вы используете w.Error() вы переопределяете content-type и соответственно используете не json а plain text. В реальности проблем может и не быть, если на клиенте нет проверки, но так делать не стоит. В целом по работе все работает, принято!

2024-05-23 19:09 UTC, robotomize commented on db/db.go
> +		repeat TEXT CHECK(length(repeat) <= 128)
Отлично, насчет констрейнтов

2024-05-23 19:09 UTC, robotomize commented on db/db.go
> +	_, err = DB.Exec(`CREATE INDEX IF NOT EXISTS date_idx ON scheduler(date);`)
Лучше это обернуть в один запрос или сделать транзакцией с предыдущим, чтобы миграция была транзакционной

2024-05-23 19:09 UTC, robotomize commented on handlers/nextdate.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Лучше создать JSON объект ошибки. Потому что приложенеи в целом с JSON работает, а через http.Error мы возвращаем content-type plain/text не очень консистентно

2024-05-23 19:09 UTC, robotomize commented on handlers/tasks.go
> +	case http.MethodPost:
Лучше разделить вот этот большой таск на несколько хэндлеров, это намного более читаемо. То есть отдельно сделать роут с POST и сделать добавление, поулчение и тд. Еще можно ваш switch case отрефакторить и каждый кейс вынести в отдельную функцию и вызывать ее, это увличит читаемость

2024-05-23 19:09 UTC, robotomize commented on handlers/tasks.go
> +		res, err := db.DB.Exec(`INSERT INTO scheduler (date, title, comment, repeat) VALUES (?, ?, ?, ?)`,
Делать запросы к базе в рамках хэндлера не очень хорошая практика, улчше разделить слой работы с БД и хэндлеры. Слой работы с БД упаковать в отдельынй пакет и пробрасывать в хэндлер как зависимость. Это можно сделать если создать хэндлер и слой работы с БД как отдельный структуры. Хэндлер принимал бы некоторый репозиторий, котоыре умеет работать с БД

2024-05-23 19:09 UTC, robotomize commented on handlers/tasks.go
> +			http.Error(w, `{"error":"Неверное тело запроса"}`, http.StatusBadRequest)
Функция Error выглядит так
```go
func Error(w ResponseWriter, error string, code int) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(code)
	fmt.Fprintln(w, error)
}
```

А вы отдаете JSON. Нужно использовать 
```go
w.Header().Set("Content-Type", "application/json; charset=UTF-8")
w.Write([]byte(`json`))
```

2024-06-15 10:35 UTC, closed without merging